#
# Example using SARIF viewer:
# https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab
#
trigger: none


pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Bash@3
    displayName: 'Snyk - Check IaC Files'
    inputs:
      targetType: 'inline'
      script: |
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/

        snyk auth $(snykToken)
        snyk iac test "$(System.DefaultWorkingDirectory)" --report --sarif-file-output="$(System.DefaultWorkingDirectory)/snyk-results.sarif"

  - task: PublishBuildArtifacts@1
    condition: always()
    displayName: 'Snyk - Publish Sarif Results'
    inputs:
      pathToPublish: $(System.DefaultWorkingDirectory)/snyk-results.sarif
      artifactName: CodeAnalysisLogs
